# Generated by Django 5.0.1 on 2024-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_of_seats', models.IntegerField()),
                ('projector', models.BooleanField(default=False)),
            ],
        ),
    ]
